### PR TITLE
Probably fixed the github button

### PR DESCRIPTION
**Pull request by TriHydera**

### CODE REVIEW

**Comment by audn** [comment]
You only added ` `. No actual code was added.

**Comment by TriHydera** [comment]
But i added the url and deleted my old `<a>` tag

**Comment by audn** [comment]
I already fixed the issue before you made the merge request, so the difference between your version, and the current one, is just a few spaces :P

**Comment by TriHydera** [comment]
> I already fixed the issue before you made the merge request, so the difference between your version, and the current one, is just a few spaces :P

So you took my idea and claim as your own before i could fix it

**Pull request closed without merging**
