### PR TITLE
Upgrade to Next 11, update dependencies, use new next/image blur placeholder

### PR DESCRIPTION
**Pull request by treboryx**

### CODE REVIEW

**Comment by audn** [comment]
Really nice!

The only thing I don't like is how repetitive the base64 url is, especially in larger applications. 

Maybe you could transform it into a function inside the `/helpers/` folder? 

That way we can call it like this: `blurDataURL={function()}`

**Review by audn — CHANGES_REQUESTED** [review]
Really nice!

The only thing I don't like is how repetitive the base64 url is, especially in larger applications. 

Maybe you could transform it into a function inside the `/helpers/` folder? 

That way we can call it like this: `blurDataURL={function()}`

**Comment by treboryx** [comment]
Does that look good?

I have also changed the Alert component, the way it's done now Next will handle the blurring, since it's a local image

**Review by audn — CHANGES_REQUESTED** [review]
Mind changing `placeholder()` to something that explains it a bit better?

`nextImagePlaceholder()` perhaps

**Comment by treboryx** [comment]
You've got it

**Pull request merged**
